# Form implementation generated from reading ui file 'create_type_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_CreateTypeDialog(object):
  def setupUi(self, CreateTypeDialog):
    CreateTypeDialog.setObjectName("CreateTypeDialog")
    CreateTypeDialog.resize(584, 375)
    self.gridLayout = QtWidgets.QGridLayout(CreateTypeDialog)
    self.gridLayout.setObjectName("gridLayout")
    self.mainVerticalLayout = QtWidgets.QVBoxLayout()
    self.mainVerticalLayout.setContentsMargins(20, -1, 20, -1)
    self.mainVerticalLayout.setObjectName("mainVerticalLayout")
    self.tileHorizontalLayout = QtWidgets.QHBoxLayout()
    self.tileHorizontalLayout.setObjectName("tileHorizontalLayout")
    self.titleLabel = QtWidgets.QLabel(parent=CreateTypeDialog)
    self.titleLabel.setMinimumSize(QtCore.QSize(120, 0))
    self.titleLabel.setObjectName("titleLabel")
    self.tileHorizontalLayout.addWidget(self.titleLabel)
    spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
    self.tileHorizontalLayout.addItem(spacerItem)
    self.titleLineEdit = QtWidgets.QLineEdit(parent=CreateTypeDialog)
    self.titleLineEdit.setObjectName("titleLineEdit")
    self.tileHorizontalLayout.addWidget(self.titleLineEdit)
    self.mainVerticalLayout.addLayout(self.tileHorizontalLayout)
    self.labelHorizontalLayout = QtWidgets.QHBoxLayout()
    self.labelHorizontalLayout.setObjectName("labelHorizontalLayout")
    self.typeLabel = QtWidgets.QLabel(parent=CreateTypeDialog)
    self.typeLabel.setMinimumSize(QtCore.QSize(120, 0))
    self.typeLabel.setObjectName("typeLabel")
    self.labelHorizontalLayout.addWidget(self.typeLabel)
    spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
    self.labelHorizontalLayout.addItem(spacerItem1)
    self.labelLineEdit = QtWidgets.QLineEdit(parent=CreateTypeDialog)
    self.labelLineEdit.setObjectName("labelLineEdit")
    self.labelHorizontalLayout.addWidget(self.labelLineEdit)
    self.mainVerticalLayout.addLayout(self.labelHorizontalLayout)
    spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
    self.mainVerticalLayout.addItem(spacerItem2)
    self.checkBoxHorizontalLayout = QtWidgets.QHBoxLayout()
    self.checkBoxHorizontalLayout.setObjectName("checkBoxHorizontalLayout")
    self.structuralLevelCheckBox = QtWidgets.QCheckBox(parent=CreateTypeDialog)
    self.structuralLevelCheckBox.setObjectName("structuralLevelCheckBox")
    self.checkBoxHorizontalLayout.addWidget(self.structuralLevelCheckBox)
    self.mainVerticalLayout.addLayout(self.checkBoxHorizontalLayout)
    self.mainVerticalLayout.setStretch(0, 1)
    self.mainVerticalLayout.setStretch(1, 1)
    self.mainVerticalLayout.setStretch(2, 1)
    self.mainVerticalLayout.setStretch(3, 1)
    self.gridLayout.addLayout(self.mainVerticalLayout, 0, 0, 1, 1)
    self.buttonBox = QtWidgets.QDialogButtonBox(parent=CreateTypeDialog)
    self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
    self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
    self.buttonBox.setObjectName("buttonBox")
    self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)

    self.retranslateUi(CreateTypeDialog)
    self.buttonBox.accepted.connect(CreateTypeDialog.accept) # type: ignore
    self.buttonBox.rejected.connect(CreateTypeDialog.reject) # type: ignore
    QtCore.QMetaObject.connectSlotsByName(CreateTypeDialog)

  def retranslateUi(self, CreateTypeDialog):
    _translate = QtCore.QCoreApplication.translate
    CreateTypeDialog.setWindowTitle(_translate("CreateTypeDialog", "Create New Type"))
    self.titleLabel.setText(_translate("CreateTypeDialog", "Enter Type title"))
    self.titleLineEdit.setToolTip(_translate("CreateTypeDialog", "Exclude titles which start with \'x\' (reserved for structure level titles) or whitespace"))
    self.titleLineEdit.setPlaceholderText(_translate("CreateTypeDialog", "Enter title for the new type"))
    self.typeLabel.setText(_translate("CreateTypeDialog", "Enter Type Label"))
    self.labelLineEdit.setToolTip(_translate("CreateTypeDialog", "Enter label for the new type, which can also be modified later in the main editor window"))
    self.labelLineEdit.setPlaceholderText(_translate("CreateTypeDialog", "Enter label for the new type"))
    self.structuralLevelCheckBox.setToolTip(_translate("CreateTypeDialog", "If this is a structural type, then title will be automatically populated as (x0, x1...xn). Next number will be chosen for xn from the existing list of structural items."))
    self.structuralLevelCheckBox.setText(_translate("CreateTypeDialog", "Is this a structural Type?"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CreateTypeDialog = QtWidgets.QDialog()
    ui = Ui_CreateTypeDialog()
    ui.setupUi(CreateTypeDialog)
    CreateTypeDialog.show()
    sys.exit(app.exec())
