# Form implementation generated from reading ui file 'dataverse_dialog_base.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_DataverseDialogBase(object):
  def setupUi(self, DataverseDialogBase):
    DataverseDialogBase.setObjectName("DataverseDialogBase")
    DataverseDialogBase.resize(900, 767)
    self.gridLayout = QtWidgets.QGridLayout(DataverseDialogBase)
    self.gridLayout.setObjectName("gridLayout")
    self.buttonBox = QtWidgets.QDialogButtonBox(parent=DataverseDialogBase)
    self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
    self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
    self.buttonBox.setObjectName("buttonBox")
    self.gridLayout.addWidget(self.buttonBox, 2, 0, 1, 1)
    self.mainVerticalLayout = QtWidgets.QVBoxLayout()
    self.mainVerticalLayout.setObjectName("mainVerticalLayout")
    self.searchBarHorizontalLayout = QtWidgets.QHBoxLayout()
    self.searchBarHorizontalLayout.setObjectName("searchBarHorizontalLayout")
    self.terminologyLineEdit = QtWidgets.QLineEdit(parent=DataverseDialogBase)
    self.terminologyLineEdit.setClearButtonEnabled(True)
    self.terminologyLineEdit.setObjectName("terminologyLineEdit")
    self.searchBarHorizontalLayout.addWidget(self.terminologyLineEdit)
    self.terminologySearchPushButton = QtWidgets.QPushButton(parent=DataverseDialogBase)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.terminologySearchPushButton.sizePolicy().hasHeightForWidth())
    self.terminologySearchPushButton.setSizePolicy(sizePolicy)
    self.terminologySearchPushButton.setMinimumSize(QtCore.QSize(150, 0))
    self.terminologySearchPushButton.setObjectName("terminologySearchPushButton")
    self.searchBarHorizontalLayout.addWidget(self.terminologySearchPushButton)
    self.mainVerticalLayout.addLayout(self.searchBarHorizontalLayout)
    self.searchProgressBar = QtWidgets.QProgressBar(parent=DataverseDialogBase)
    self.searchProgressBar.setProperty("value", 0)
    self.searchProgressBar.setObjectName("searchProgressBar")
    self.mainVerticalLayout.addWidget(self.searchProgressBar)
    self.scrollAreaHorizontalLayout = QtWidgets.QHBoxLayout()
    self.scrollAreaHorizontalLayout.setObjectName("scrollAreaHorizontalLayout")
    self.listView = QtWidgets.QListView(parent=DataverseDialogBase)
    self.listView.setObjectName("listView")
    self.scrollAreaHorizontalLayout.addWidget(self.listView)
    self.mainVerticalLayout.addLayout(self.scrollAreaHorizontalLayout)
    self.uploadButtonHorizontalLayout = QtWidgets.QHBoxLayout()
    self.uploadButtonHorizontalLayout.setObjectName("uploadButtonHorizontalLayout")
    self.uploadPushButton = QtWidgets.QPushButton(parent=DataverseDialogBase)
    self.uploadPushButton.setMinimumSize(QtCore.QSize(150, 0))
    self.uploadPushButton.setObjectName("uploadPushButton")
    self.uploadButtonHorizontalLayout.addWidget(self.uploadPushButton)
    spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
    self.uploadButtonHorizontalLayout.addItem(spacerItem)
    self.mainVerticalLayout.addLayout(self.uploadButtonHorizontalLayout)
    self.errorConsoleVerticalLayout = QtWidgets.QVBoxLayout()
    self.errorConsoleVerticalLayout.setObjectName("errorConsoleVerticalLayout")
    self.errorButtonsHorizontalLayout = QtWidgets.QHBoxLayout()
    self.errorButtonsHorizontalLayout.setObjectName("errorButtonsHorizontalLayout")
    self.errorConsolePushButton = QtWidgets.QPushButton(parent=DataverseDialogBase)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.errorConsolePushButton.sizePolicy().hasHeightForWidth())
    self.errorConsolePushButton.setSizePolicy(sizePolicy)
    self.errorConsolePushButton.setMinimumSize(QtCore.QSize(150, 0))
    self.errorConsolePushButton.setObjectName("errorConsolePushButton")
    self.errorButtonsHorizontalLayout.addWidget(self.errorConsolePushButton)
    spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
    self.errorButtonsHorizontalLayout.addItem(spacerItem1)
    self.errorConsoleVerticalLayout.addLayout(self.errorButtonsHorizontalLayout)
    self.errorConsoleTextEdit = QtWidgets.QTextEdit(parent=DataverseDialogBase)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.errorConsoleTextEdit.sizePolicy().hasHeightForWidth())
    self.errorConsoleTextEdit.setSizePolicy(sizePolicy)
    self.errorConsoleTextEdit.setMinimumSize(QtCore.QSize(0, 0))
    self.errorConsoleTextEdit.setObjectName("errorConsoleTextEdit")
    self.errorConsoleVerticalLayout.addWidget(self.errorConsoleTextEdit)
    self.mainVerticalLayout.addLayout(self.errorConsoleVerticalLayout)
    self.gridLayout.addLayout(self.mainVerticalLayout, 0, 0, 1, 1)

    self.retranslateUi(DataverseDialogBase)
    self.buttonBox.accepted.connect(DataverseDialogBase.accept) # type: ignore
    self.buttonBox.rejected.connect(DataverseDialogBase.reject) # type: ignore
    QtCore.QMetaObject.connectSlotsByName(DataverseDialogBase)

  def retranslateUi(self, DataverseDialogBase):
    _translate = QtCore.QCoreApplication.translate
    DataverseDialogBase.setWindowTitle(_translate("DataverseDialogBase", "Dataverse Upload"))
    self.terminologyLineEdit.setPlaceholderText(_translate("DataverseDialogBase", "\"Search for Definitions in Wikis/Ontologies\""))
    self.terminologySearchPushButton.setText(_translate("DataverseDialogBase", "Search"))
    self.uploadPushButton.setText(_translate("DataverseDialogBase", "Upload"))
    self.errorConsolePushButton.setText(_translate("DataverseDialogBase", "Show/Hide Errors"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DataverseDialogBase = QtWidgets.QDialog()
    ui = Ui_DataverseDialogBase()
    ui.setupUi(DataverseDialogBase)
    DataverseDialogBase.show()
    sys.exit(app.exec())
