# Form implementation generated from reading ui file 'dataverse_config_upload_dialog_base.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_ConfigUploadDialog(object):
  def setupUi(self, ConfigUploadDialog):
    ConfigUploadDialog.setObjectName("ConfigUploadDialog")
    ConfigUploadDialog.resize(255, 196)
    self.verticalLayout = QtWidgets.QVBoxLayout(ConfigUploadDialog)
    self.verticalLayout.setObjectName("verticalLayout")
    self.projectContentsScrollArea = QtWidgets.QScrollArea(parent=ConfigUploadDialog)
    self.projectContentsScrollArea.setWidgetResizable(True)
    self.projectContentsScrollArea.setObjectName("projectContentsScrollArea")
    self.scrollAreaWidgetContents = QtWidgets.QWidget()
    self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 221, 159))
    self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
    self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
    self.verticalLayout_3.setObjectName("verticalLayout_3")
    self.projectItemsVerticalLayout = QtWidgets.QVBoxLayout()
    self.projectItemsVerticalLayout.setObjectName("projectItemsVerticalLayout")
    self.checkBox = QtWidgets.QCheckBox(parent=self.scrollAreaWidgetContents)
    self.checkBox.setChecked(True)
    self.checkBox.setObjectName("checkBox")
    self.projectItemsVerticalLayout.addWidget(self.checkBox)
    self.checkBox_3 = QtWidgets.QCheckBox(parent=self.scrollAreaWidgetContents)
    self.checkBox_3.setChecked(True)
    self.checkBox_3.setObjectName("checkBox_3")
    self.projectItemsVerticalLayout.addWidget(self.checkBox_3)
    self.checkBox_5 = QtWidgets.QCheckBox(parent=self.scrollAreaWidgetContents)
    self.checkBox_5.setChecked(True)
    self.checkBox_5.setObjectName("checkBox_5")
    self.projectItemsVerticalLayout.addWidget(self.checkBox_5)
    self.checkBox_4 = QtWidgets.QCheckBox(parent=self.scrollAreaWidgetContents)
    self.checkBox_4.setChecked(True)
    self.checkBox_4.setObjectName("checkBox_4")
    self.projectItemsVerticalLayout.addWidget(self.checkBox_4)
    self.checkBox_2 = QtWidgets.QCheckBox(parent=self.scrollAreaWidgetContents)
    self.checkBox_2.setChecked(True)
    self.checkBox_2.setObjectName("checkBox_2")
    self.projectItemsVerticalLayout.addWidget(self.checkBox_2)
    self.verticalLayout_3.addLayout(self.projectItemsVerticalLayout)
    self.projectContentsScrollArea.setWidget(self.scrollAreaWidgetContents)
    self.verticalLayout.addWidget(self.projectContentsScrollArea)
    self.buttonBox = QtWidgets.QDialogButtonBox(parent=ConfigUploadDialog)
    self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
    self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
    self.buttonBox.setObjectName("buttonBox")
    self.verticalLayout.addWidget(self.buttonBox)

    self.retranslateUi(ConfigUploadDialog)
    self.buttonBox.accepted.connect(ConfigUploadDialog.accept) # type: ignore
    self.buttonBox.rejected.connect(ConfigUploadDialog.reject) # type: ignore
    QtCore.QMetaObject.connectSlotsByName(ConfigUploadDialog)

  def retranslateUi(self, ConfigUploadDialog):
    _translate = QtCore.QCoreApplication.translate
    ConfigUploadDialog.setWindowTitle(_translate("ConfigUploadDialog", "Configure project upload"))
    ConfigUploadDialog.setToolTip(_translate("ConfigUploadDialog", "Select the project items to be uploaded to dataverse."))
    self.checkBox.setText(_translate("ConfigUploadDialog", "Measurements"))
    self.checkBox_3.setText(_translate("ConfigUploadDialog", "Samples"))
    self.checkBox_5.setText(_translate("ConfigUploadDialog", "Procedures"))
    self.checkBox_4.setText(_translate("ConfigUploadDialog", "Instruments"))
    self.checkBox_2.setText(_translate("ConfigUploadDialog", "Unidentified"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ConfigUploadDialog = QtWidgets.QDialog()
    ui = Ui_ConfigUploadDialog()
    ui.setupUi(ConfigUploadDialog)
    ConfigUploadDialog.show()
    sys.exit(app.exec())
