# Form implementation generated from reading ui file 'dataverse_compound_frame_base.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_CompoundFrame(object):
  def setupUi(self, CompoundFrame):
    CompoundFrame.setObjectName("CompoundFrame")
    CompoundFrame.resize(1345, 101)
    CompoundFrame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
    self.verticalLayout = QtWidgets.QVBoxLayout(CompoundFrame)
    self.verticalLayout.setObjectName("verticalLayout")
    self.mainVerticalLayout = QtWidgets.QVBoxLayout()
    self.mainVerticalLayout.setObjectName("mainVerticalLayout")
    self.addPushButton = QtWidgets.QPushButton(parent=CompoundFrame)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.addPushButton.sizePolicy().hasHeightForWidth())
    self.addPushButton.setSizePolicy(sizePolicy)
    self.addPushButton.setMinimumSize(QtCore.QSize(100, 0))
    self.addPushButton.setObjectName("addPushButton")
    self.mainVerticalLayout.addWidget(self.addPushButton)
    self.compoundHorizontalLayout = QtWidgets.QHBoxLayout()
    self.compoundHorizontalLayout.setObjectName("compoundHorizontalLayout")
    self.mainVerticalLayout.addLayout(self.compoundHorizontalLayout)
    self.verticalLayout.addLayout(self.mainVerticalLayout)

    self.retranslateUi(CompoundFrame)
    QtCore.QMetaObject.connectSlotsByName(CompoundFrame)

  def retranslateUi(self, CompoundFrame):
    _translate = QtCore.QCoreApplication.translate
    CompoundFrame.setWindowTitle(_translate("CompoundFrame", "Frame"))
    CompoundFrame.setToolTip(_translate("CompoundFrame", "Set the compound type for metadata block."))
    self.addPushButton.setToolTip(_translate("CompoundFrame", "Add a new compound entry to the list."))
    self.addPushButton.setText(_translate("CompoundFrame", "Add"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CompoundFrame = QtWidgets.QFrame()
    ui = Ui_CompoundFrame()
    ui.setupUi(CompoundFrame)
    CompoundFrame.show()
    sys.exit(app.exec())
