# Form implementation generated from reading ui file 'dataverse_completed_uploads_base.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_DataverseCompletedUploadsForm(object):
  def setupUi(self, DataverseCompletedUploadsForm):
    DataverseCompletedUploadsForm.setObjectName("DataverseCompletedUploadsForm")
    DataverseCompletedUploadsForm.resize(765, 503)
    self.gridLayout = QtWidgets.QGridLayout(DataverseCompletedUploadsForm)
    self.gridLayout.setObjectName("gridLayout")
    self.mainVerticalLayout = QtWidgets.QVBoxLayout()
    self.mainVerticalLayout.setObjectName("mainVerticalLayout")
    self.completedUploadsScrollArea = QtWidgets.QScrollArea(parent=DataverseCompletedUploadsForm)
    self.completedUploadsScrollArea.setWidgetResizable(True)
    self.completedUploadsScrollArea.setObjectName("completedUploadsScrollArea")
    self.scrollAreaWidgetContents = QtWidgets.QWidget()
    self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 743, 448))
    self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
    self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
    self.verticalLayout_3.setObjectName("verticalLayout_3")
    self.completedUploadsVerticalLayout = QtWidgets.QVBoxLayout()
    self.completedUploadsVerticalLayout.setObjectName("completedUploadsVerticalLayout")
    self.verticalLayout_3.addLayout(self.completedUploadsVerticalLayout)
    self.completedUploadsScrollArea.setWidget(self.scrollAreaWidgetContents)
    self.mainVerticalLayout.addWidget(self.completedUploadsScrollArea)
    self.buttonsHorizontalLayout = QtWidgets.QHBoxLayout()
    self.buttonsHorizontalLayout.setObjectName("buttonsHorizontalLayout")
    spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
    self.buttonsHorizontalLayout.addItem(spacerItem)
    self.selectAllPushButton = QtWidgets.QPushButton(parent=DataverseCompletedUploadsForm)
    self.selectAllPushButton.setObjectName("selectAllPushButton")
    self.buttonsHorizontalLayout.addWidget(self.selectAllPushButton)
    self.deselectAllPushButton = QtWidgets.QPushButton(parent=DataverseCompletedUploadsForm)
    self.deselectAllPushButton.setObjectName("deselectAllPushButton")
    self.buttonsHorizontalLayout.addWidget(self.deselectAllPushButton)
    self.clearSelectedPushButton = QtWidgets.QPushButton(parent=DataverseCompletedUploadsForm)
    self.clearSelectedPushButton.setObjectName("clearSelectedPushButton")
    self.buttonsHorizontalLayout.addWidget(self.clearSelectedPushButton)
    self.mainVerticalLayout.addLayout(self.buttonsHorizontalLayout)
    self.gridLayout.addLayout(self.mainVerticalLayout, 0, 0, 1, 1)

    self.retranslateUi(DataverseCompletedUploadsForm)
    QtCore.QMetaObject.connectSlotsByName(DataverseCompletedUploadsForm)

  def retranslateUi(self, DataverseCompletedUploadsForm):
    _translate = QtCore.QCoreApplication.translate
    DataverseCompletedUploadsForm.setWindowTitle(_translate("DataverseCompletedUploadsForm", "Dataverse Upload History"))
    self.completedUploadsScrollArea.setToolTip(_translate("DataverseCompletedUploadsForm", "<html><head/><body><p><span style=\" font-style:italic;\">Displays the history of finished dataverse uploads done in the past.</span></p></body></html>"))
    self.selectAllPushButton.setToolTip(_translate("DataverseCompletedUploadsForm", "Select all the above listed upload tasks."))
    self.selectAllPushButton.setText(_translate("DataverseCompletedUploadsForm", "Select All"))
    self.deselectAllPushButton.setToolTip(_translate("DataverseCompletedUploadsForm", "Deselect all above listed upload tasks."))
    self.deselectAllPushButton.setText(_translate("DataverseCompletedUploadsForm", "Deselect All"))
    self.clearSelectedPushButton.setToolTip(_translate("DataverseCompletedUploadsForm", "Delete all the selected tasks in the above given list."))
    self.clearSelectedPushButton.setText(_translate("DataverseCompletedUploadsForm", "Clear Selected"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DataverseCompletedUploadsForm = QtWidgets.QWidget()
    ui = Ui_DataverseCompletedUploadsForm()
    ui.setupUi(DataverseCompletedUploadsForm)
    DataverseCompletedUploadsForm.show()
    sys.exit(app.exec())
