# Form implementation generated from reading ui file 'dataverse_edit_metadata_dialog_base.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_EditMetadataDialog(object):
  def setupUi(self, EditMetadataDialog):
    EditMetadataDialog.setObjectName("EditMetadataDialog")
    EditMetadataDialog.resize(1143, 227)
    self.verticalLayout = QtWidgets.QVBoxLayout(EditMetadataDialog)
    self.verticalLayout.setObjectName("verticalLayout")
    self.mainVerticalLayout = QtWidgets.QVBoxLayout()
    self.mainVerticalLayout.setObjectName("mainVerticalLayout")
    self.metadataBlockComboBox = QtWidgets.QComboBox(parent=EditMetadataDialog)
    self.metadataBlockComboBox.setObjectName("metadataBlockComboBox")
    self.mainVerticalLayout.addWidget(self.metadataBlockComboBox)
    self.typesComboBox = QtWidgets.QComboBox(parent=EditMetadataDialog)
    self.typesComboBox.setObjectName("typesComboBox")
    self.mainVerticalLayout.addWidget(self.typesComboBox)
    self.metadataScrollArea = QtWidgets.QScrollArea(parent=EditMetadataDialog)
    self.metadataScrollArea.setWidgetResizable(True)
    self.metadataScrollArea.setObjectName("metadataScrollArea")
    self.scrollAreaWidgetContents = QtWidgets.QWidget()
    self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1121, 112))
    self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
    self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
    self.verticalLayout_3.setObjectName("verticalLayout_3")
    self.metadataScrollVerticalLayout = QtWidgets.QVBoxLayout()
    self.metadataScrollVerticalLayout.setObjectName("metadataScrollVerticalLayout")
    self.verticalLayout_3.addLayout(self.metadataScrollVerticalLayout)
    self.metadataScrollArea.setWidget(self.scrollAreaWidgetContents)
    self.mainVerticalLayout.addWidget(self.metadataScrollArea)
    self.verticalLayout.addLayout(self.mainVerticalLayout)
    self.buttonBox = QtWidgets.QDialogButtonBox(parent=EditMetadataDialog)
    self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
    self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Discard|QtWidgets.QDialogButtonBox.StandardButton.Save)
    self.buttonBox.setObjectName("buttonBox")
    self.verticalLayout.addWidget(self.buttonBox)

    self.retranslateUi(EditMetadataDialog)
    self.buttonBox.accepted.connect(EditMetadataDialog.accept) # type: ignore
    self.buttonBox.rejected.connect(EditMetadataDialog.reject) # type: ignore
    QtCore.QMetaObject.connectSlotsByName(EditMetadataDialog)

  def retranslateUi(self, EditMetadataDialog):
    _translate = QtCore.QCoreApplication.translate
    EditMetadataDialog.setWindowTitle(_translate("EditMetadataDialog", "Dialog"))
    self.metadataBlockComboBox.setToolTip(_translate("EditMetadataDialog", "Select the metadata block to be edited."))
    self.typesComboBox.setToolTip(_translate("EditMetadataDialog", "Select the metadata block type to be edited."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EditMetadataDialog = QtWidgets.QDialog()
    ui = Ui_EditMetadataDialog()
    ui.setupUi(EditMetadataDialog)
    EditMetadataDialog.show()
    sys.exit(app.exec())
