# Form implementation generated from reading ui file 'dataverse_upload_widget_base.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_ProjectUploadForm(object):
  def setupUi(self, ProjectUploadForm):
    ProjectUploadForm.setObjectName("ProjectUploadForm")
    ProjectUploadForm.setEnabled(True)
    ProjectUploadForm.resize(1171, 73)
    self.gridLayout = QtWidgets.QGridLayout(ProjectUploadForm)
    self.gridLayout.setObjectName("gridLayout")
    self.uploadWidgetHorizontalLayout = QtWidgets.QHBoxLayout()
    self.uploadWidgetHorizontalLayout.setObjectName("uploadWidgetHorizontalLayout")
    self.uploadProjectLabel = QtWidgets.QLabel(parent=ProjectUploadForm)
    self.uploadProjectLabel.setObjectName("uploadProjectLabel")
    self.uploadWidgetHorizontalLayout.addWidget(self.uploadProjectLabel)
    self.uploadProgressBar = QtWidgets.QProgressBar(parent=ProjectUploadForm)
    self.uploadProgressBar.setProperty("value", 24)
    self.uploadProgressBar.setObjectName("uploadProgressBar")
    self.uploadWidgetHorizontalLayout.addWidget(self.uploadProgressBar)
    self.showLogPushButton = QtWidgets.QPushButton(parent=ProjectUploadForm)
    icon = QtGui.QIcon.fromTheme("document-page-setup")
    self.showLogPushButton.setIcon(icon)
    self.showLogPushButton.setObjectName("showLogPushButton")
    self.uploadWidgetHorizontalLayout.addWidget(self.showLogPushButton)
    self.uploadCancelPushButton = QtWidgets.QPushButton(parent=ProjectUploadForm)
    icon = QtGui.QIcon.fromTheme("window-close")
    self.uploadCancelPushButton.setIcon(icon)
    self.uploadCancelPushButton.setObjectName("uploadCancelPushButton")
    self.uploadWidgetHorizontalLayout.addWidget(self.uploadCancelPushButton)
    self.gridLayout.addLayout(self.uploadWidgetHorizontalLayout, 0, 0, 1, 1)

    self.retranslateUi(ProjectUploadForm)
    QtCore.QMetaObject.connectSlotsByName(ProjectUploadForm)

  def retranslateUi(self, ProjectUploadForm):
    _translate = QtCore.QCoreApplication.translate
    ProjectUploadForm.setWindowTitle(_translate("ProjectUploadForm", "UploadWidget"))
    self.uploadProjectLabel.setText(_translate("ProjectUploadForm", "Example Project 1"))
    self.showLogPushButton.setText(_translate("ProjectUploadForm", "Show Log"))
    self.uploadCancelPushButton.setText(_translate("ProjectUploadForm", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ProjectUploadForm = QtWidgets.QWidget()
    ui = Ui_ProjectUploadForm()
    ui.setupUi(ProjectUploadForm)
    ProjectUploadForm.show()
    sys.exit(app.exec())
