# Form implementation generated from reading ui file 'dataverse_completed_upload_task.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_CompletedUploadTaskFrame(object):
  def setupUi(self, CompletedUploadTaskFrame):
    CompletedUploadTaskFrame.setObjectName("CompletedUploadTaskFrame")
    CompletedUploadTaskFrame.resize(1051, 73)
    CompletedUploadTaskFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
    CompletedUploadTaskFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
    self.horizontalLayout_2 = QtWidgets.QHBoxLayout(CompletedUploadTaskFrame)
    self.horizontalLayout_2.setObjectName("horizontalLayout_2")
    self.horizontalLayout = QtWidgets.QHBoxLayout()
    self.horizontalLayout.setObjectName("horizontalLayout")
    self.selectCheckBox = QtWidgets.QCheckBox(parent=CompletedUploadTaskFrame)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.selectCheckBox.sizePolicy().hasHeightForWidth())
    self.selectCheckBox.setSizePolicy(sizePolicy)
    self.selectCheckBox.setMinimumSize(QtCore.QSize(20, 0))
    self.selectCheckBox.setText("")
    self.selectCheckBox.setObjectName("selectCheckBox")
    self.horizontalLayout.addWidget(self.selectCheckBox)
    self.projectNameLabel = QtWidgets.QLabel(parent=CompletedUploadTaskFrame)
    self.projectNameLabel.setObjectName("projectNameLabel")
    self.horizontalLayout.addWidget(self.projectNameLabel)
    self.dataverseUrlLabel = QtWidgets.QLabel(parent=CompletedUploadTaskFrame)
    self.dataverseUrlLabel.setObjectName("dataverseUrlLabel")
    self.horizontalLayout.addWidget(self.dataverseUrlLabel)
    self.finishedDateTimeEdit = QtWidgets.QDateTimeEdit(parent=CompletedUploadTaskFrame)
    self.finishedDateTimeEdit.setReadOnly(True)
    self.finishedDateTimeEdit.setObjectName("finishedDateTimeEdit")
    self.horizontalLayout.addWidget(self.finishedDateTimeEdit)
    self.horizontalLayout_2.addLayout(self.horizontalLayout)

    self.retranslateUi(CompletedUploadTaskFrame)
    QtCore.QMetaObject.connectSlotsByName(CompletedUploadTaskFrame)

  def retranslateUi(self, CompletedUploadTaskFrame):
    _translate = QtCore.QCoreApplication.translate
    CompletedUploadTaskFrame.setWindowTitle(_translate("CompletedUploadTaskFrame", "Frame"))
    self.selectCheckBox.setToolTip(_translate("CompletedUploadTaskFrame", "Select to clear the upload task from the history."))
    self.projectNameLabel.setToolTip(_translate("CompletedUploadTaskFrame", "PASTA project name which was uploaded to dataverse."))
    self.projectNameLabel.setText(_translate("CompletedUploadTaskFrame", "Example Project 1"))
    self.dataverseUrlLabel.setToolTip(_translate("CompletedUploadTaskFrame", "The dataverse URL where the PASTA project was uploaded."))
    self.dataverseUrlLabel.setText(_translate("CompletedUploadTaskFrame", "Dataverse URL"))
    self.finishedDateTimeEdit.setToolTip(_translate("CompletedUploadTaskFrame", "The dataverse upload time."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CompletedUploadTaskFrame = QtWidgets.QFrame()
    ui = Ui_CompletedUploadTaskFrame()
    ui.setupUi(CompletedUploadTaskFrame)
    CompletedUploadTaskFrame.show()
    sys.exit(app.exec())
