WORKPLAN_TEMPLATE = ['# common workflow description v1.0; head of workflow: always the same\n',
                     'from urllib.parse import urlparse\n',
                     'from common_workflow_description import Storage, Sample, step\n',
                     'try:\n',
                     '    from pyiron_workflow import Workflow\n',
                     'except ImportError:\n',
                     '    from common_workflow_description import Workflow\n',
                     'from analysis_steps import plot_curves, calc_YoungsModulus\n',
                     '\n', "wf = Workflow('{workplan_name}', automate_execution=False)\n",
                     "proceduresLibrary = urlparse('{library_url}')\n",
                     'storage=Storage(proceduresLibrary)\n',
                     "sample = Sample('{sample_name}')\n",
                     '\n',
                     'wf.starting_nodes = [wf.step0]\n',
                     '\n',
                     '# footer, always the same\n',
                     'print(\'Output:\\n  \',\'\\n   \'.join([f"{k}: {v}" for k, v in list(wf.outputs.to_value_dict().items())]))\n',
                     'wf.draw().render(filename="io_demo", format="png", cleanup=True) #plot to file\n',
                     '\n',
                     '# Automatically Created by Workflow Creator']
