# Form implementation generated from reading ui file 'primitive_compound_controller_frame_base.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_PrimitiveCompoundControlledBaseFrame(object):
  def setupUi(self, PrimitiveCompoundControlledBaseFrame):
    PrimitiveCompoundControlledBaseFrame.setObjectName("PrimitiveCompoundControlledBaseFrame")
    PrimitiveCompoundControlledBaseFrame.resize(1345, 101)
    PrimitiveCompoundControlledBaseFrame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
    self.verticalLayout = QtWidgets.QVBoxLayout(PrimitiveCompoundControlledBaseFrame)
    self.verticalLayout.setObjectName("verticalLayout")
    self.mainVerticalLayout = QtWidgets.QVBoxLayout()
    self.mainVerticalLayout.setObjectName("mainVerticalLayout")
    self.addPushButton = QtWidgets.QPushButton(parent=PrimitiveCompoundControlledBaseFrame)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.addPushButton.sizePolicy().hasHeightForWidth())
    self.addPushButton.setSizePolicy(sizePolicy)
    self.addPushButton.setMinimumSize(QtCore.QSize(100, 0))
    self.addPushButton.setObjectName("addPushButton")
    self.mainVerticalLayout.addWidget(self.addPushButton)
    self.verticalLayout.addLayout(self.mainVerticalLayout)

    self.retranslateUi(PrimitiveCompoundControlledBaseFrame)
    QtCore.QMetaObject.connectSlotsByName(PrimitiveCompoundControlledBaseFrame)

  def retranslateUi(self, PrimitiveCompoundControlledBaseFrame):
    _translate = QtCore.QCoreApplication.translate
    PrimitiveCompoundControlledBaseFrame.setWindowTitle(_translate("PrimitiveCompoundControlledBaseFrame", "Frame"))
    PrimitiveCompoundControlledBaseFrame.setToolTip(_translate("PrimitiveCompoundControlledBaseFrame", "Set the compound type for metadata block."))
    self.addPushButton.setToolTip(_translate("PrimitiveCompoundControlledBaseFrame", "Add a new compound entry to the list."))
    self.addPushButton.setText(_translate("PrimitiveCompoundControlledBaseFrame", "Add"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PrimitiveCompoundControlledBaseFrame = QtWidgets.QFrame()
    ui = Ui_PrimitiveCompoundControlledBaseFrame()
    ui.setupUi(PrimitiveCompoundControlledBaseFrame)
    PrimitiveCompoundControlledBaseFrame.show()
    sys.exit(app.exec())
