# Form implementation generated from reading ui file 'ui_thread_tests_base.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_UIThreadTestsDialog(object):
  def setupUi(self, UIThreadTestsDialog):
    UIThreadTestsDialog.setObjectName("UIThreadTestsDialog")
    UIThreadTestsDialog.resize(559, 482)
    self.verticalLayout_2 = QtWidgets.QVBoxLayout(UIThreadTestsDialog)
    self.verticalLayout_2.setObjectName("verticalLayout_2")
    self.mainVerticalLayout = QtWidgets.QVBoxLayout()
    self.mainVerticalLayout.setObjectName("mainVerticalLayout")
    self.clickLabel = QtWidgets.QLabel(parent=UIThreadTestsDialog)
    self.clickLabel.setObjectName("clickLabel")
    self.mainVerticalLayout.addWidget(self.clickLabel)
    self.clickPushButton = QtWidgets.QPushButton(parent=UIThreadTestsDialog)
    self.clickPushButton.setObjectName("clickPushButton")
    self.mainVerticalLayout.addWidget(self.clickPushButton)
    spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
    self.mainVerticalLayout.addItem(spacerItem)
    self.label4 = QtWidgets.QLabel(parent=UIThreadTestsDialog)
    self.label4.setText("")
    self.label4.setObjectName("label4")
    self.mainVerticalLayout.addWidget(self.label4)
    self.progressBar4 = QtWidgets.QProgressBar(parent=UIThreadTestsDialog)
    self.progressBar4.setProperty("value", 0)
    self.progressBar4.setObjectName("progressBar4")
    self.mainVerticalLayout.addWidget(self.progressBar4)
    self.progressPushButton4 = QtWidgets.QPushButton(parent=UIThreadTestsDialog)
    self.progressPushButton4.setObjectName("progressPushButton4")
    self.mainVerticalLayout.addWidget(self.progressPushButton4)
    self.label3 = QtWidgets.QLabel(parent=UIThreadTestsDialog)
    self.label3.setText("")
    self.label3.setObjectName("label3")
    self.mainVerticalLayout.addWidget(self.label3)
    self.progressBar3 = QtWidgets.QProgressBar(parent=UIThreadTestsDialog)
    self.progressBar3.setProperty("value", 0)
    self.progressBar3.setObjectName("progressBar3")
    self.mainVerticalLayout.addWidget(self.progressBar3)
    self.progressPushButton3 = QtWidgets.QPushButton(parent=UIThreadTestsDialog)
    self.progressPushButton3.setObjectName("progressPushButton3")
    self.mainVerticalLayout.addWidget(self.progressPushButton3)
    self.label2 = QtWidgets.QLabel(parent=UIThreadTestsDialog)
    self.label2.setText("")
    self.label2.setObjectName("label2")
    self.mainVerticalLayout.addWidget(self.label2)
    self.progressBar2 = QtWidgets.QProgressBar(parent=UIThreadTestsDialog)
    self.progressBar2.setProperty("value", 0)
    self.progressBar2.setObjectName("progressBar2")
    self.mainVerticalLayout.addWidget(self.progressBar2)
    self.progressPushButton2 = QtWidgets.QPushButton(parent=UIThreadTestsDialog)
    self.progressPushButton2.setObjectName("progressPushButton2")
    self.mainVerticalLayout.addWidget(self.progressPushButton2)
    self.label1 = QtWidgets.QLabel(parent=UIThreadTestsDialog)
    self.label1.setText("")
    self.label1.setObjectName("label1")
    self.mainVerticalLayout.addWidget(self.label1)
    self.progressBar1 = QtWidgets.QProgressBar(parent=UIThreadTestsDialog)
    self.progressBar1.setProperty("value", 0)
    self.progressBar1.setObjectName("progressBar1")
    self.mainVerticalLayout.addWidget(self.progressBar1)
    self.progressPushButton1 = QtWidgets.QPushButton(parent=UIThreadTestsDialog)
    self.progressPushButton1.setObjectName("progressPushButton1")
    self.mainVerticalLayout.addWidget(self.progressPushButton1)
    self.verticalLayout_2.addLayout(self.mainVerticalLayout)
    self.buttonBox = QtWidgets.QDialogButtonBox(parent=UIThreadTestsDialog)
    self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
    self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
    self.buttonBox.setObjectName("buttonBox")
    self.verticalLayout_2.addWidget(self.buttonBox)

    self.retranslateUi(UIThreadTestsDialog)
    self.buttonBox.accepted.connect(UIThreadTestsDialog.accept) # type: ignore
    self.buttonBox.rejected.connect(UIThreadTestsDialog.reject) # type: ignore
    QtCore.QMetaObject.connectSlotsByName(UIThreadTestsDialog)

  def retranslateUi(self, UIThreadTestsDialog):
    _translate = QtCore.QCoreApplication.translate
    UIThreadTestsDialog.setWindowTitle(_translate("UIThreadTestsDialog", "UI Thread Tests"))
    self.clickLabel.setText(_translate("UIThreadTestsDialog", "Clicked: 0"))
    self.clickPushButton.setText(_translate("UIThreadTestsDialog", "Click"))
    self.progressPushButton4.setText(_translate("UIThreadTestsDialog", "doProgress4"))
    self.progressPushButton3.setText(_translate("UIThreadTestsDialog", "doProgress3"))
    self.progressPushButton2.setText(_translate("UIThreadTestsDialog", "doProgress2"))
    self.progressPushButton1.setText(_translate("UIThreadTestsDialog", "doProgress1"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    UIThreadTestsDialog = QtWidgets.QDialog()
    ui = Ui_UIThreadTestsDialog()
    ui.setupUi(UIThreadTestsDialog)
    UIThreadTestsDialog.show()
    sys.exit(app.exec())
